# Generated by Django 4.2 on 2024-02-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
