# Generated by Django 4.2 on 2024-02-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_userresponse_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='session_key',
            field=models.CharField(default='default_session_key', max_length=40),
        ),
    ]
