# Generated by Django 4.2 on 2024-02-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_userresponse_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='global_question_id',
            field=models.IntegerField(default=1),
        ),
    ]
